---

#_____________________________________
# restart galaxy inside docker using supervisorctl

- name: user creation 
  become_user: root
  command: docker exec galaxydocker /bin/bash -c ". $GALAXY_VIRTUAL_ENV/bin/activate; python /usr/local/bin/create_galaxy_user.py --user {{ GALAXY_ADMIN_EMAIL }} --password {{ GALAXY_ADMIN_PASSWORD }} -c $GALAXY_CONFIG_FILE  --key {{ GALAXY_ADMIN_API_KEY }} --username {{ GALAXY_ADMIN_EMAIL }} ; deactivate "

#_____________________________________
#install pip module needed for delete_user python script

  #- name: pip module install 
  #  become_user: root
  #  command: docker exec galaxydocker /bin/bash -c "pip install social-auth-core SQLAlchemy routes webob paste bleach babel psycopg2-binary numpy boltons pyyaml "

#_____________________________________
#run delete user python script

- name: delete-user 
  become_user: root
  command: docker exec galaxydocker /bin/bash -c ". $GALAXY_VIRTUAL_ENV/bin/activate;  python /etc/galaxy/delete_galaxy_user.py -u admin@galaxy.org -c /etc/galaxy/galaxy.yml; deactivate "
  ignore_errors: yes

#_____________________________________
#test if there is the wf directory

- name: test workflow directory
  become_user: root
  command: docker exec galaxydocker /bin/bash -c "test -d /home/galaxy/workflows "
  register: testdir
  ignore_errors: yes

#_____________________________________
#share workflow with admin user

- name: share wf
  become_user: root
  command: docker exec galaxydocker /bin/bash -c ". $GALAXY_VIRTUAL_ENV/bin/activate;  workflow-install --workflow_path $GALAXY_HOME/workflows/ -g http://localhost:80 -u {{ GALAXY_ADMIN_EMAIL }} -p {{ GALAXY_ADMIN_PASSWORD }} "
  when: testdir|success and galaxy_flavor != 'alvera/galaxy_vinyl:20.05' 

- name: share wf vinyl
  become_user: root
  command: docker exec galaxydocker /tool_deps/_conda/bin/workflow-install --workflow_path /home/galaxy/workflows/ -g http://localhost:80 -u {{ GALAXY_ADMIN_EMAIL }} -p {{ GALAXY_ADMIN_PASSWORD }}
  when: testdir|success and galaxy_flavor == 'alvera/galaxy_vinyl:20.05' 

